# change postgresql version to ver.10 instead of latest
FROM postgres:10
MAINTAINER Limbas GmbH <info@limbas.com>

# add limbas demo data, will be imported automatically
ADD demo.sql /docker-entrypoint-initdb.d/import.sql

CMD ["postgres"]
